import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export type Language = 'en' | 'ar';

interface LanguageStore {
  language: Language;
  setLanguage: (lang: Language) => void;
}

export const useLanguage = create<LanguageStore>()(
  persist(
    (set) => ({
      language: 'en',
      setLanguage: (lang) => set({ language: lang }),
    }),
    {
      name: 'language-storage',
    }
  )
);

export const t = (key: string, lang: Language): string => {
  const translations: Record<string, Record<Language, string>> = {
    'edit': { 'en': 'Edit', 'ar': 'تعديل' },
    'delete': { 'en': 'Delete', 'ar': 'حذف' },
    'language': { 'en': 'Language', 'ar': 'اللغة' },
    'english': { 'en': 'English', 'ar': 'English' },
    'arabic': { 'en': 'العربية', 'ar': 'العربية' },
    'search': { 'en': 'Search', 'ar': 'البحث' },
    'make': { 'en': 'Make', 'ar': 'الماركة' },
    'model': { 'en': 'Model', 'ar': 'الموديل' },
    'year': { 'en': 'Year', 'ar': 'سنة' },
    'destination': { 'en': 'Destination', 'ar': 'الوجهة' },
    'status': { 'en': 'Status', 'ar': 'الحالة' },
    'auction': { 'en': 'Auction', 'ar': 'المزاد' },
    'branch': { 'en': 'Branch', 'ar': 'الفرع' },
    'select_auction': { 'en': 'Select Auction', 'ar': 'اختر المزاد' },
    'select_branch': { 'en': 'Select Branch', 'ar': 'اختر الفرع' },
    'auction_details': { 'en': 'Auction Details', 'ar': 'تفاصيل المزاد' },
    'fuel_type': { 'en': 'Fuel Type', 'ar': 'نوع الوقود' },
    'hybrid': { 'en': 'Hybrid', 'ar': 'هايبرد' },
    'electric': { 'en': 'Electric', 'ar': 'كهربائي' },
    'confirm_delete_auction': { 'en': 'Are you sure you want to delete this auction?', 'ar': 'هل أنت متأكد من حذف هذا المزاد؟' },
    'confirm_delete_branch': { 'en': 'Are you sure you want to delete this branch?', 'ar': 'هل أنت متأكد من حذف هذا الفرع؟' },
    'title_key': { 'en': 'Title & Key', 'ar': 'التايتل والمفاتيح' },
    'title_present': { 'en': 'Title Present', 'ar': 'التايتل موجود' },
    'key_present': { 'en': 'Key Present', 'ar': 'المفاتيح موجودة' },
    'container_number': { 'en': 'Container Number', 'ar': 'رقم الحاوية' },
    'booking_number': { 'en': 'Booking Number', 'ar': 'رقم الحجز' },
    'etd': { 'en': 'ETD (Departure)', 'ar': 'تاريخ المغادرة' },
    'eta': { 'en': 'ETA (Arrival)', 'ar': 'تاريخ الوصول' },
    'photos_documents': { 'en': 'Photos & Documents', 'ar': 'الصور والمستندات' },
    'warehouse_pictures': { 'en': 'Warehouse Pictures', 'ar': 'صور المستودع' },
    'loading_pictures': { 'en': 'Loading Pictures', 'ar': 'صور التحميل' },
    'uploading_pictures': { 'en': 'Uploading Pictures', 'ar': 'صور التحميل' },
    'unloading_pictures': { 'en': 'Unloading Pictures', 'ar': 'صور التفريغ' },
    'auction_pictures': { 'en': 'Auction Pictures', 'ar': 'صور المزاد' },
    'download_all': { 'en': 'Download All', 'ar': 'تحميل الكل' },
    'no_photos': { 'en': 'No photos', 'ar': 'لا توجد صور' },
    'no_invoice_uploaded': { 'en': 'No invoice uploaded', 'ar': 'لم يتم تحميل فاتورة' },
    'invoice': { 'en': 'Invoice', 'ar': 'الفاتورة' },
    'logout': { 'en': 'Log Out', 'ar': 'تسجيل الخروج' },
    'my_vehicles': { 'en': 'My vehicles', 'ar': 'سياراتي' },
    'my_garage': { 'en': 'My Garage', 'ar': 'سياراتي' },
    'vin': { 'en': 'VIN', 'ar': 'رقم الهيكل' },
    'lot': { 'en': 'LOT', 'ar': 'رقم القطعة' },
    'vehicle': { 'en': 'Vehicle', 'ar': 'السيارة' },
    'all_makes': { 'en': 'All Makes', 'ar': 'جميع الماركات' },
    'all_years': { 'en': 'All Years', 'ar': 'جميع السنوات' },
    'all_destinations': { 'en': 'All Destinations', 'ar': 'جميع الوجهات' },
    'title_ok': { 'en': 'TITLE OK', 'ar': 'التايتل موجود' },
    'no_title': { 'en': 'NO TITLE', 'ar': 'لا يوجد التايتل' },
    'key': { 'en': 'KEY', 'ar': 'المفاتيح' },
    'no_key': { 'en': 'NO KEY', 'ar': 'لا توجد مفاتيح' },
    'system_settings': { 'en': 'System Settings', 'ar': 'إعدادات النظام' },
    'users': { 'en': 'Users', 'ar': 'المستخدمون' },
    'vehicle_details': { 'en': 'Vehicle Details', 'ar': 'تفاصيل السيارة' },
    'notes': { 'en': 'Notes', 'ar': 'ملاحظات' },
    'admin_notes': { 'en': 'Admin Notes', 'ar': 'ملاحظات المسؤول' },
    'logistics_info': { 'en': 'Logistics Information', 'ar': 'معلومات الخدمات اللوجستية' },
    'send_buyer': { 'en': 'Send to Buyer', 'ar': 'إرسال للمشتري' },
    'save_update': { 'en': 'Save & Update', 'ar': 'حفظ وتحديث' },
    'add': { 'en': '+ Add', 'ar': '+ إضافة' },
    'upload_invoice': { 'en': '+ Upload Invoice', 'ar': '+ تحميل الفاتورة' },
    'manage_assigned': { 'en': 'Manage and track your assigned vehicles.', 'ar': 'إدارة ومتابعة السيارات المخصصة لك.' },
    'owner': { 'en': 'Owner', 'ar': 'المالك' },
    'assigned_to': { 'en': 'Owner', 'ar': 'المالك' },
    'select_owner': { 'en': 'Select Owner', 'ar': 'اختر المالك' },
    'photo_deleted': { 'en': 'Photo Deleted', 'ar': 'تم حذف الصورة' },
    'portal_access': { 'en': 'Portal Access', 'ar': 'دخول البوابة' },
    'sign_in': { 'en': 'Sign In', 'ar': 'دخول' },
    'username': { 'en': 'Username', 'ar': 'اسم المستخدم' },
    'password': { 'en': 'Password', 'ar': 'كلمة المرور' },
    'enter_username': { 'en': 'Enter your username', 'ar': 'أدخل اسم المستخدم' },
    'enter_password': { 'en': 'Enter your password', 'ar': 'أدخل كلمة المرور' },
    'demo': { 'en': 'Demo:', 'ar': 'تجربة:' },
    'welcome_back': { 'en': 'Welcome back', 'ar': 'أهلا وسهلا' },
    'successfully_logged_in': { 'en': 'Successfully logged in.', 'ar': 'تم تسجيل الدخول بنجاح.' },
    'login_failed': { 'en': 'Login Failed', 'ar': 'فشل تسجيل الدخول' },
    'invalid_credentials': { 'en': 'Invalid username or password.', 'ar': 'اسم مستخدم أو كلمة مرور غير صحيحة.' },
    'add_vehicle': { 'en': 'Add Vehicle', 'ar': 'إضافة مركبة' },
    'add_new_vehicle': { 'en': 'Add New Vehicle', 'ar': 'إضافة مركبة جديدة' },
    'enter_vehicle_details': { 'en': 'Enter the vehicle details below.', 'ar': 'أدخل تفاصيل المركبة أدناه.' },
    'vin_hash': { 'en': 'VIN #', 'ar': 'رقم الهيكل #' },
    'lot_hash': { 'en': 'LOT #', 'ar': 'رقم القطعة #' },
    'select_make': { 'en': 'Select Make...', 'ar': 'اختر الماركة...' },
    'select_model': { 'en': 'Select Model...', 'ar': 'اختر الموديل...' },
    'no_make_found': { 'en': 'No make found.', 'ar': 'لم يتم العثور على ماركة.' },
    'no_model_found': { 'en': 'No model found.', 'ar': 'لم يتم العثور على موديل.' },
    'search_make': { 'en': 'Search make...', 'ar': 'ابحث عن الماركة...' },
    'search_model': { 'en': 'Search model...', 'ar': 'ابحث عن الموديل...' },
    'select_destination': { 'en': 'Select Destination', 'ar': 'اختر الوجهة' },
    'select_user': { 'en': 'Select a User', 'ar': 'اختر مستخدم' },
    'title_available': { 'en': 'Title Available', 'ar': 'التايتل متاح' },
    'key_available': { 'en': 'Key Available', 'ar': 'المفاتيح متاحة' },
    'assign_to_user': { 'en': 'Assign To User', 'ar': 'تعيين للمستخدم' },
    'any_public_notes': { 'en': 'Any public notes...', 'ar': 'أي ملاحظات عامة...' },
    'admin_note_internal': { 'en': 'Admin Note (Internal Only)', 'ar': 'ملاحظة المسؤول (داخلي فقط)' },
    'private_admin_notes': { 'en': 'Private admin notes...', 'ar': 'ملاحظات المسؤول الخاصة...' },
    'save_vehicle': { 'en': 'Save Vehicle', 'ar': 'حفظ المركبة' },
    'manage_users': { 'en': 'Manage system users and their roles.', 'ar': 'إدارة مستخدمي النظام وأدوارهم.' },
    'access_denied': { 'en': 'Access Denied', 'ar': 'تم رفض الوصول' },
    'no_permission': { 'en': 'You do not have permission to view this page.', 'ar': 'ليس لديك إذن لعرض هذه الصفحة.' },
    'add_user': { 'en': '+ Add User', 'ar': '+ إضافة مستخدم' },
    'add_user_simple': { 'en': 'Add User', 'ar': 'إضافة مستخدم' },
    'create_new_user': { 'en': 'Create New User', 'ar': 'إنشاء مستخدم جديد' },
    'add_new_user_portal': { 'en': 'Add a new user who can access the portal.', 'ar': 'أضف مستخدم جديد يمكنه الوصول إلى البوابة.' },
    'create_user': { 'en': 'Create User', 'ar': 'إنشاء مستخدم' },
    'user_created': { 'en': 'User Created', 'ar': 'تم إنشاء المستخدم' },
    'user_added_system': { 'en': 'New user has been added to the system.', 'ar': 'تم إضافة مستخدم جديد إلى النظام.' },
    'edit_user': { 'en': 'Edit User', 'ar': 'تعديل المستخدم' },
    'user_updated': { 'en': 'User Updated', 'ar': 'تم تحديث المستخدم' },
    'user_details_saved': { 'en': 'User details saved.', 'ar': 'تم حفظ بيانات المستخدم.' },
    'save_changes': { 'en': 'Save Changes', 'ar': 'حفظ التغييرات' },
    'secret_password': { 'en': 'Secret123', 'ar': 'كلمة سرية123' },
    'select_role': { 'en': 'Select Role', 'ar': 'اختر الدور' },
    'admin': { 'en': 'Admin', 'ar': 'مسؤول' },
    'user': { 'en': 'User', 'ar': 'مستخدم' },
    'role': { 'en': 'Role:', 'ar': 'الدور:' },
    'email': { 'en': 'Email', 'ar': 'البريد الإلكتروني' },
    'full_name': { 'en': 'Full Name', 'ar': 'الاسم الكامل' },
    'car_added': { 'en': 'Car Added', 'ar': 'تمت إضافة السيارة' },
    'vehicle_added_system': { 'en': 'New vehicle has been added to the system.', 'ar': 'تمت إضافة مركبة جديدة إلى النظام.' },
    'saved': { 'en': 'Saved', 'ar': 'تم الحفظ' },
    'vehicle_details_updated': { 'en': 'Vehicle details updated successfully.', 'ar': 'تم تحديث تفاصيل المركبة بنجاح.' },
    'email_sent': { 'en': 'Email Sent', 'ar': 'تم إرسال البريد' },
    'update_sent_buyer': { 'en': 'Update notification sent to the buyer.', 'ar': 'تم إرسال إشعار التحديث للمشتري.' },
    'photos_uploaded': { 'en': 'Photos Uploaded', 'ar': 'تم تحميل الصور' },
    'invoice_uploaded': { 'en': 'Invoice Uploaded', 'ar': 'تم تحميل الفاتورة' },
    'container': { 'en': 'Container #', 'ar': 'الحاوية #' },
    'booking': { 'en': 'Booking #', 'ar': 'الحجز #' },
    'etd_departure': { 'en': 'ETD (Estimated Time of Departure)', 'ar': 'موعد المغادرة المتوقع' },
    'eta_arrival': { 'en': 'ETA (Estimated Time of Arrival)', 'ar': 'موعد الوصول المتوقع' },
    'vehicle_invoice': { 'en': 'Vehicle Invoice', 'ar': 'فاتورة المركبة' },
    'pdf_image_document': { 'en': 'PDF / Image Document', 'ar': 'وثيقة PDF / صورة' },
    'view': { 'en': 'View', 'ar': 'عرض' },
    'download': { 'en': 'Download', 'ar': 'تحميل' },
    'delete_invoice': { 'en': 'Delete Invoice', 'ar': 'حذف الفاتورة' },
    'invoice_deleted': { 'en': 'Invoice Deleted', 'ar': 'تم حذف الفاتورة' },
    'no_vehicles_found': { 'en': 'No vehicles found matching your criteria.', 'ar': 'لم يتم العثور على مركبات تطابق معاييرك.' },
    'vin_lot_model': { 'en': 'VIN, Lot, Model...', 'ar': 'رقم الهيكل، رقم القطعة، الموديل...' },
    'confirm_delete': { 'en': 'Confirm Delete', 'ar': 'تأكيد الحذف' },
    'confirm_delete_vehicle': { 'en': 'Are you sure you want to delete this vehicle? This action cannot be undone.', 'ar': 'هل أنت متأكد من حذف هذه المركبة؟ لا يمكن التراجع عن هذا الإجراء.' },
    'confirm_delete_user': { 'en': 'Are you sure you want to delete this user? This action cannot be undone.', 'ar': 'هل أنت متأكد من حذف هذا المستخدم؟ لا يمكن التراجع عن هذا الإجراء.' },
    'confirm_delete_invoice': { 'en': 'Are you sure you want to delete this invoice?', 'ar': 'هل أنت متأكد من حذف هذه الفاتورة؟' },
    'confirm_delete_make': { 'en': 'Are you sure you want to delete this make?', 'ar': 'هل أنت متأكد من حذف هذه الماركة؟' },
    'confirm_delete_model': { 'en': 'Are you sure you want to delete this model?', 'ar': 'هل أنت متأكد من حذف هذا الموديل؟' },
    'confirm_delete_destination': { 'en': 'Are you sure you want to delete this destination?', 'ar': 'هل أنت متأكد من حذف هذه الوجهة؟' },
    'cancel': { 'en': 'Cancel', 'ar': 'إلغاء' },
    'upload_failed': { 'en': 'Upload Failed', 'ar': 'فشل التحميل' },
    'confirm_delete_photo': { 'en': 'Are you sure you want to delete this photo?', 'ar': 'هل أنت متأكد من حذف هذه الصورة؟' },
    'duplicate_vin': { 'en': 'Duplicate VIN', 'ar': 'رقم الهيكل مكرر' },
    'duplicate_vin_message': { 'en': 'A vehicle with this VIN already exists in the system.', 'ar': 'توجد مركبة بهذا رقم الهيكل في النظام.' },
    'error': { 'en': 'Error', 'ar': 'خطأ' },
    'add_vehicle_failed': { 'en': 'Failed to add vehicle', 'ar': 'فشل في إضافة المركبة' },
    'delete_all': { 'en': 'Delete All', 'ar': 'حذف الكل' },
    'confirm_delete_all': { 'en': 'Confirm Delete All', 'ar': 'تأكيد حذف الكل' },
    'confirm_delete_all_photos': { 'en': 'Are you sure you want to delete all photos in {section}? This action cannot be undone.', 'ar': 'هل أنت متأكد من حذف جميع الصور في {section}؟ لا يمكن التراجع عن هذا الإجراء.' },
    'delete_failed': { 'en': 'Delete Failed', 'ar': 'فشل الحذف' },
    'photos_deleted': { 'en': 'Photos Deleted', 'ar': 'تم حذف الصور' },
    'invoice_document': { 'en': 'Invoice & Document', 'ar': 'الفاتورة والمستندات' },
    'carfax': { 'en': 'CARFAX', 'ar': 'CARFAX' },
    'contact_us': { 'en': 'Contact Us', 'ar': 'اتصل بنا' },
  };
  return translations[key]?.[lang] || key;
};
